services:
    app:
        container_name: homework_07_app
        build:
            context: .  # Сборка из текущей директории
            
            dockerfile: characters-app/Dockerfile  # Путь к Dockerfile
            
        env_file:
            - .env  # Переменные окружения из .env (.env итак по-умолчанию)
        
        ports:
            - "8000:8000"

        command: >
            sh -c "if [ ! -f /.initialized ]; then
                echo 'Running initial setup...';
                python manage.py migrate;
                python manage.py generate_test_data;
                touch /.initialized;
                echo 'Starting server...';
            fi &&
            gunicorn config.wsgi:application --workers 4 --bind 0.0.0.0:8000"
        depends_on:
            pg:
                condition: service_healthy  # Ждём, пока БД не станет доступна
    

    pg:
        container_name: homework_07_postgres
        image: postgres:15

        env_file:
            - .env # Переменные окружения из файла .env (.env итак по-умолчанию)
        
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "${POSTGRES_PORT}:5432"
        
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 2s
            timeout: 3s
            retries: 3



volumes:
    postgres_data:
        name: homework_07_volume